### PR TITLE
DOC-662 interrupted communication after private networking

### PR DESCRIPTION
**Pull request by micheleRP**
## Description

This adds a tip to the AWS Private Link, Azure PrivateLink, and GCP Private Service Connect pages to alert users that as soon as the private service is available on your VPC, all communication on existing Redpanda public ports is interrupted & to have apps running in your VPC ready to start using the corresponding private ports.

Resolves https://redpandadata.atlassian.net/browse/DOC-662
Review deadline: Dec 12

## Page previews

- [AWS PrivateLink API](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/aws-privatelink/)
- [Azure Private Link API](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/azure-private-link/)
- [GCP API](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/gcp-private-service-connect/)
- [AWS PrivateLink UI](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/configure-privatelink-in-cloud-ui/)
- [GCP UI](https://deploy-preview-154--rp-cloud.netlify.app/redpanda-cloud/networking/configure-private-service-connect-in-cloud-ui/)

## Checks

- [ ] New feature
- [ ] Content gap
- [X] Support Follow-up
- [ ] Small fix (typos, links, copyedits, etc)

### CODE REVIEW

**Review by Deflaimun — APPROVED** [review]
there seems to be a lot of repetition. Consider adding this into a partial

**Comment by micheleRP** [comment]
> there seems to be a lot of repetition. Consider adding this into a partial

@Deflaimun the names are different for each cloud service, and the tip is different for API vs UI

**Comment by Deflaimun** [comment]
You can use a conditional partial to mention the specific cloud provider. So that your partial can look like 
`This content is for the {provider} provider.`

and when you use it you can do 
´include::partial$your-file.adoc[provider="AWS"]`




But it's your call if you want to do that.

**Comment by micheleRP** [comment]
approved by Masa in slack

**Pull request merged**
